Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/nbextensions.py", line 32, in <module>
    from traitlets.config.manager import BaseJSONConfigManager
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 17, in <module>
    from decorator import decorator
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/decorator.py", line 33, in <module>
    """
KeyboardInterrupt
[I 22:27:15.922 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 22:27:15.926 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[W 22:27:18.581 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 22:27:19.793 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 22:27:19.793 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 22:27:19.797 NotebookApp] [nb_conda] enabled
[I 22:27:21.645 NotebookApp] [nb_anacondacloud] enabled
[I 22:27:21.648 NotebookApp] Serving notebooks from local directory: /home/ubuntu/fish
[I 22:27:21.648 NotebookApp] 0 active kernels 
[I 22:27:21.648 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 22:27:21.648 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 22:30:09.812 NotebookApp] 302 GET / (176.61.36.2) 0.64ms
[I 22:30:09.833 NotebookApp] 302 GET /tree (176.61.36.2) 0.94ms
[I 22:30:15.628 NotebookApp] 302 POST /login?next=%2Ftree (176.61.36.2) 0.85ms
[W 22:30:29.366 NotebookApp] Notebook feat/CheckDarknet2103.ipynb is not trusted
[I 22:30:29.730 NotebookApp] Kernel started: 354e101c-b6e3-407c-92f4-b062d092d7d7
[I 22:32:48.811 NotebookApp] Kernel restarted: 354e101c-b6e3-407c-92f4-b062d092d7d7
[I 22:34:29.723 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:35:02.559 NotebookApp] Kernel restarted: 354e101c-b6e3-407c-92f4-b062d092d7d7
[I 22:36:29.732 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:38:02.254 NotebookApp] Kernel restarted: 354e101c-b6e3-407c-92f4-b062d092d7d7
[I 22:38:29.734 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:40:30.166 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:42:29.727 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:46:29.762 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:48:29.786 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:52:29.719 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:54:29.909 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:55:16.726 NotebookApp] Kernel restarted: 354e101c-b6e3-407c-92f4-b062d092d7d7
[I 22:56:29.728 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:56:47.824 NotebookApp] Kernel restarted: 354e101c-b6e3-407c-92f4-b062d092d7d7
[W 22:57:34.481 NotebookApp] Notebook resnet/resnet_07-yolo544-flip.ipynb is not trusted
[I 22:57:36.351 NotebookApp] Kernel started: 2ab13410-cfe2-4bf9-a4c2-155718aa4f34
[I 22:57:39.814 NotebookApp] Copying resnet/resnet_07-yolo544-flip.ipynb to /resnet
[W 22:57:39.870 NotebookApp] Notebook resnet/resnet_07-yolo544-flip.ipynb is not trusted
[W 22:57:39.901 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo544-flip-Copy1.ipynb
[W 22:57:40.724 NotebookApp] Notebook resnet/resnet_07-yolo544-flip-Copy1.ipynb is not trusted
[I 22:57:42.162 NotebookApp] Kernel started: 88585b30-4e47-4094-a7a3-81dc7f24657a
[I 22:58:29.723 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 22:59:42.613 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[W 22:59:42.614 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo640.ipynb
[I 23:01:42.587 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[W 23:01:42.588 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo640.ipynb
[I 23:02:29.846 NotebookApp] Saving file at /feat/CheckDarknet2103.ipynb
[I 23:03:42.626 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[W 23:03:42.627 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo640.ipynb
[I 23:05:42.780 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[W 23:05:42.781 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo640.ipynb
[I 23:07:42.537 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[W 23:07:42.537 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo640.ipynb
[I 23:08:11.483 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[W 23:08:11.483 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo640.ipynb
[I 23:08:30.149 NotebookApp] Kernel restarted: 88585b30-4e47-4094-a7a3-81dc7f24657a
[I 23:08:31.026 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[I 23:08:35.059 NotebookApp] Kernel restarted: 88585b30-4e47-4094-a7a3-81dc7f24657a
[I 23:09:42.468 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[I 23:11:42.486 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[I 23:13:42.642 NotebookApp] Saving file at /resnet/resnet_07-yolo640.ipynb
[I 11:54:48.991 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 11:54:49.074 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[W 11:54:51.282 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 11:54:52.297 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 11:54:52.297 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 11:54:52.301 NotebookApp] [nb_conda] enabled
[I 11:54:53.424 NotebookApp] [nb_anacondacloud] enabled
[I 11:54:53.427 NotebookApp] Serving notebooks from local directory: /home/ubuntu/fish
[I 11:54:53.427 NotebookApp] 0 active kernels 
[I 11:54:53.427 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 11:54:53.427 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 11:55:04.672 NotebookApp] 302 GET / (176.61.36.2) 0.62ms
[I 11:55:04.690 NotebookApp] 302 GET /tree (176.61.36.2) 0.81ms
[I 11:55:10.163 NotebookApp] 302 POST /login?next=%2Ftree (176.61.36.2) 0.87ms
[I 11:58:20.078 NotebookApp] Kernel started: f87fcc0b-f07d-4131-8820-2abc9ce8f983
[I 11:58:43.314 NotebookApp] Kernel shutdown: f87fcc0b-f07d-4131-8820-2abc9ce8f983
[I 11:58:50.927 NotebookApp] Copying resnet/resnet_06-Squarebox.ipynb to /resnet
[I 11:58:51.644 NotebookApp] Copying resnet/resnet_07-yolo544-flip.ipynb to /resnet
[W 11:58:52.057 NotebookApp] Notebook resnet/resnet_07-yolo544-flip.ipynb is not trusted
[W 11:58:52.087 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo544-flip-Copy1.ipynb
[W 11:59:08.624 NotebookApp] delete /resnet/resnet_06-Squarebox-Copy1.ipynb
[W 11:59:25.565 NotebookApp] Notebook resnet/resnet_07-yolo544-revise.ipynb is not trusted
[I 11:59:26.642 NotebookApp] Kernel started: 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad
[I 11:59:37.360 NotebookApp] Kernel restarted: 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad
[I 12:01:27.558 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:02:57.920 NotebookApp] Kernel restarted: 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad
[I 12:03:26.691 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:05:26.692 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:07:26.679 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:09:26.678 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:11:26.691 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:13:26.755 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:15:27.588 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:17:26.693 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:19:26.687 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:21:26.696 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:23:26.803 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:25:26.728 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:25:37.581 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:26:48.242 NotebookApp] Kernel restarted: 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad
[I 12:27:26.676 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:29:26.701 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:31:26.663 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:31:30.766 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:31:49.133 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:32:14.430 NotebookApp] Kernel restarted: 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad
[I 12:33:27.911 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:35:27.898 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 12:40:46.733 NotebookApp] Kernel restarted: 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[I 12:40:49.736 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[I 12:40:52.745 NotebookApp] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[I 12:40:55.754 NotebookApp] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[I 12:40:58.764 NotebookApp] KernelRestarter: restarting kernel (4/5)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[W 12:41:01.773 NotebookApp] KernelRestarter: restart failed
[W 12:41:01.774 NotebookApp] Kernel 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad died, removing from map.
[W 12:41:01.774 NotebookApp] Restarting kernel failed: 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad
[E 12:41:01.774 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 88, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    RuntimeError: Restart failed
[E 12:41:01.776 NotebookApp] {
      "Origin": "http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888", 
      "Content-Length": "0", 
      "Accept-Language": "en-GB,en-US;q=0.8,en;q=0.6", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_07-yolo544-revise.ipynb", 
      "Cookie": "username-ec2-34-248-253-103-eu-west-1-compute-amazonaws-com-8888=\"2|1:0|10:1490529310|64:username-ec2-34-248-253-103-eu-west-1-compute-amazonaws-com-8888|48:ZjFjYzA3ZmQtOGU5Ny00MTVmLTk0YTAtMmZmZDFhZmFiNWVl|66b0ed822dd8ffe8120ec4166dd3cb0e5b099ea928a9e26fa6dae7528b8e0cf9\""
    }
[E 12:41:01.776 NotebookApp] 500 POST /api/kernels/06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad/restart (176.61.36.2) 16070.06ms referer=http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_07-yolo544-revise.ipynb
[I 12:41:27.361 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[E 12:41:30.750 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 88, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 109, in restart_kernel
        self._check_kernel_id(kernel_id)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 169, in _check_kernel_id
        raise web.HTTPError(404, u'Kernel does not exist: %s' % kernel_id)
    HTTPError: HTTP 404: Not Found (Kernel does not exist: 06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad)
[E 12:41:30.751 NotebookApp] {
      "Origin": "http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888", 
      "Content-Length": "0", 
      "Accept-Language": "en-GB,en-US;q=0.8,en;q=0.6", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_07-yolo544-revise.ipynb", 
      "Cookie": "username-ec2-34-248-253-103-eu-west-1-compute-amazonaws-com-8888=\"2|1:0|10:1490529310|64:username-ec2-34-248-253-103-eu-west-1-compute-amazonaws-com-8888|48:ZjFjYzA3ZmQtOGU5Ny00MTVmLTk0YTAtMmZmZDFhZmFiNWVl|66b0ed822dd8ffe8120ec4166dd3cb0e5b099ea928a9e26fa6dae7528b8e0cf9\""
    }
[E 12:41:30.752 NotebookApp] 500 POST /api/kernels/06b4b5eb-6ecd-47fd-9cf2-9204df5d5dad/restart (176.61.36.2) 1.72ms referer=http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_07-yolo544-revise.ipynb
[E 12:51:43.548 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
        yielded = self.gen.send(value)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 57, in post
        model = yield gen.maybe_future(sm.get_session(path=path))
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 166, in get_session
        return self.row_to_model(row)
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 205, in row_to_model
        raise KeyError
    KeyError
[E 12:51:43.550 NotebookApp] {
      "Origin": "http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888", 
      "Content-Length": "105", 
      "Accept-Language": "en-GB,en-US;q=0.8,en;q=0.6", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_07-yolo544-revise.ipynb", 
      "Cookie": "username-ec2-34-248-253-103-eu-west-1-compute-amazonaws-com-8888=\"2|1:0|10:1490529310|64:username-ec2-34-248-253-103-eu-west-1-compute-amazonaws-com-8888|48:ZjFjYzA3ZmQtOGU5Ny00MTVmLTk0YTAtMmZmZDFhZmFiNWVl|66b0ed822dd8ffe8120ec4166dd3cb0e5b099ea928a9e26fa6dae7528b8e0cf9\"", 
      "Content-Type": "application/json"
    }
[E 12:51:43.550 NotebookApp] 500 POST /api/sessions (176.61.36.2) 3.78ms referer=http://ec2-34-248-253-103.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_07-yolo544-revise.ipynb
[I 12:52:01.864 NotebookApp] Kernel started: 1f3b9de6-60a0-4a62-8d2b-cc5e54c08d5d
[I 12:52:22.900 NotebookApp] Kernel interrupted: 1f3b9de6-60a0-4a62-8d2b-cc5e54c08d5d
[I 12:52:35.740 NotebookApp] Kernel interrupted: 1f3b9de6-60a0-4a62-8d2b-cc5e54c08d5d
[I 12:52:43.509 NotebookApp] Kernel restarted: 1f3b9de6-60a0-4a62-8d2b-cc5e54c08d5d
[I 12:53:18.966 NotebookApp] Kernel restarted: 1f3b9de6-60a0-4a62-8d2b-cc5e54c08d5d
[I 12:53:33.353 NotebookApp] Kernel restarted: 1f3b9de6-60a0-4a62-8d2b-cc5e54c08d5d
[I 12:54:02.227 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 16:14:02.033 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 17:24:49.239 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 17:24:49.328 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[W 17:24:51.614 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 17:24:52.138 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 17:24:52.139 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 17:24:52.143 NotebookApp] [nb_conda] enabled
[I 17:24:53.382 NotebookApp] [nb_anacondacloud] enabled
[I 17:24:53.384 NotebookApp] Serving notebooks from local directory: /home/ubuntu/fish
[I 17:24:53.384 NotebookApp] 0 active kernels 
[I 17:24:53.385 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 17:24:53.385 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 17:26:53.980 NotebookApp] 302 GET / (176.61.36.2) 0.59ms
[I 17:26:54.021 NotebookApp] 302 GET /tree (176.61.36.2) 0.81ms
[I 17:27:03.544 NotebookApp] 302 POST /login?next=%2Ftree (176.61.36.2) 0.87ms
[W 17:27:32.664 NotebookApp] Notebook resnet/resnet_08_Nof.ipynb is not trusted
[I 17:27:33.857 NotebookApp] Kernel started: 9d384fea-e4d1-4b38-a479-4ebc9d46e70c
[I 17:29:34.721 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:29:34.722 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:31:34.245 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:31:34.246 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:33:34.856 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:33:34.857 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:35:34.216 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:35:34.217 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:37:34.222 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:37:34.223 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:39:34.228 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:39:34.229 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:41:34.240 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:41:34.241 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:43:34.703 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:43:34.703 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:45:34.705 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:45:34.706 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:47:34.238 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:47:34.238 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:49:34.287 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:49:34.288 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:51:34.222 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:51:34.223 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:53:34.238 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:53:34.239 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:54:34.465 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:54:34.466 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:55:34.332 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:55:34.333 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:57:34.224 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:57:34.224 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 17:59:34.295 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 17:59:34.296 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:01:34.216 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 18:01:34.217 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:03:34.200 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 18:03:34.201 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:05:34.199 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 18:05:34.200 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:07:34.195 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 18:07:34.196 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:09:34.208 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 18:09:34.209 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:11:34.201 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 18:11:34.202 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:13:34.237 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 18:13:34.238 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:15:34.195 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[W 18:15:34.196 NotebookApp] Saving untrusted notebook resnet/resnet_08_Nof.ipynb
[I 18:17:36.289 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:25:33.878 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:27:33.858 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:29:33.856 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:31:33.870 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:33:33.858 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:35:33.864 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:37:33.863 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:39:34.363 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:41:34.658 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:43:34.624 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:54:03.883 NotebookApp] Kernel restarted: 9d384fea-e4d1-4b38-a479-4ebc9d46e70c
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[I 18:54:06.885 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[I 18:54:09.895 NotebookApp] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[I 18:54:12.905 NotebookApp] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[I 18:54:15.915 NotebookApp] KernelRestarter: restarting kernel (4/5)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 445, in initialize
    self.init_sockets()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 235, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 177, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5327)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9542)
    raise ZMQError(errno)
ZMQError: Address already in use
[W 18:54:18.924 NotebookApp] KernelRestarter: restart failed
[W 18:54:18.925 NotebookApp] Kernel 9d384fea-e4d1-4b38-a479-4ebc9d46e70c died, removing from map.
[W 18:54:18.925 NotebookApp] Restarting kernel failed: 9d384fea-e4d1-4b38-a479-4ebc9d46e70c
[E 18:54:18.925 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 88, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    RuntimeError: Restart failed
[E 18:54:18.927 NotebookApp] {
      "Origin": "http://ec2-34-253-33-71.eu-west-1.compute.amazonaws.com:8888", 
      "Content-Length": "0", 
      "Accept-Language": "en-GB,en-US;q=0.8,en;q=0.6", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "ec2-34-253-33-71.eu-west-1.compute.amazonaws.com:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://ec2-34-253-33-71.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_08_Nof.ipynb", 
      "Cookie": "username-ec2-34-253-33-71-eu-west-1-compute-amazonaws-com-8888=\"2|1:0|10:1490549223|62:username-ec2-34-253-33-71-eu-west-1-compute-amazonaws-com-8888|48:MWJkZjUzZjYtYWZlMS00Njk0LWI4ZTItODhmZThkYmExN2Y2|5dcc79bdc7fd4b397baed431e18567eb888af4ed89b0a08a164515d74b7319bc\""
    }
[E 18:54:18.927 NotebookApp] 500 POST /api/kernels/9d384fea-e4d1-4b38-a479-4ebc9d46e70c/restart (176.61.36.2) 16068.38ms referer=http://ec2-34-253-33-71.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_08_Nof.ipynb
[W 18:54:18.955 NotebookApp] Kernel deleted before session
[W 18:54:18.956 NotebookApp] 410 DELETE /api/sessions/e3bc8b0f-6752-4013-9ded-0a4e7f5deeb3 (176.61.36.2) 2.47ms referer=http://ec2-34-253-33-71.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_08_Nof.ipynb
[W 18:54:21.822 NotebookApp] Session not found: session_id=u'e3bc8b0f-6752-4013-9ded-0a4e7f5deeb3'
[W 18:54:21.822 NotebookApp] 404 DELETE /api/sessions/e3bc8b0f-6752-4013-9ded-0a4e7f5deeb3 (176.61.36.2) 0.95ms referer=http://ec2-34-253-33-71.eu-west-1.compute.amazonaws.com:8888/notebooks/resnet/resnet_08_Nof.ipynb
[I 18:54:22.376 NotebookApp] Kernel started: 1f869ea1-f782-4a86-afa0-489b91077a92
[I 18:54:49.190 NotebookApp] Kernel restarted: 1f869ea1-f782-4a86-afa0-489b91077a92
[I 18:55:34.250 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:59:34.715 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 21:49:32.489 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 21:49:41.567 NotebookApp] Kernel started: af59ad64-227f-4a80-9164-e3a97296fc42
[I 21:50:05.073 NotebookApp] Saving file at /resnet/resnet_07-yolo544-revise.ipynb
[I 21:50:14.986 NotebookApp] Kernel shutdown: af59ad64-227f-4a80-9164-e3a97296fc42
[W 21:50:21.746 NotebookApp] Notebook resnet/resnet_07-yolo544-flip.ipynb is not trusted
[I 21:50:22.799 NotebookApp] Kernel started: 0b1ee591-3d86-4ffd-82dd-3dcf44dbc561
[I 21:50:34.055 NotebookApp] Saving file at /resnet/resnet_07-yolo544-flip.ipynb
[W 21:50:34.057 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo544-flip.ipynb
[I 21:50:40.449 NotebookApp] Kernel shutdown: 0b1ee591-3d86-4ffd-82dd-3dcf44dbc561
[I 22:13:34.624 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 01:15:34.518 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 03:39:34.365 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 06:43:34.439 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 07:17:34.054 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 07:21:17.753 NotebookApp] 302 GET /notebooks/sub/subm_full_resnet_NoF_cut0.7_20170327.csv (176.61.36.2) 0.91ms
[I 07:30:48.866 NotebookApp] Kernel started: 214bf5d9-2c01-4d51-b3c8-33a8c213e7d5
[I 07:31:33.903 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 07:33:33.923 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 07:35:33.823 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 07:37:10.349 NotebookApp] Kernel interrupted: 1f869ea1-f782-4a86-afa0-489b91077a92
[I 07:37:33.808 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 07:37:41.728 NotebookApp] Kernel interrupted: 1f869ea1-f782-4a86-afa0-489b91077a92
[I 07:38:07.558 NotebookApp] Kernel interrupted: 1f869ea1-f782-4a86-afa0-489b91077a92
[I 07:39:34.109 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 08:13:34.087 NotebookApp] Saving file at /resnet/resnet_08_Nof.ipynb
[I 18:55:11.624 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 18:55:11.821 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[W 18:55:15.116 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 18:55:15.787 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 18:55:15.787 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 18:55:15.791 NotebookApp] [nb_conda] enabled
[I 18:55:17.235 NotebookApp] [nb_anacondacloud] enabled
[I 18:55:17.238 NotebookApp] Serving notebooks from local directory: /home/ubuntu/fish
[I 18:55:17.238 NotebookApp] 0 active kernels 
[I 18:55:17.238 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 18:55:17.238 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 19:05:03.165 NotebookApp] 302 GET / (176.61.36.2) 0.60ms
[I 19:05:03.238 NotebookApp] 302 GET /tree (176.61.36.2) 0.86ms
[I 19:05:12.943 NotebookApp] 302 POST /login?next=%2Ftree (176.61.36.2) 0.91ms
[I 19:05:39.533 NotebookApp] Copying resnet/resnet_07-yolo544-flip.ipynb to /resnet
[W 19:05:40.488 NotebookApp] Notebook resnet/resnet_07-yolo544-flip.ipynb is not trusted
[W 19:05:40.518 NotebookApp] Saving untrusted notebook resnet/resnet_07-yolo544-flip-Copy1.ipynb
[I 19:06:17.161 NotebookApp] Copying resnet/zztest_resnet_07-yolo544-0.5.ipynb to /resnet
[W 19:06:17.211 NotebookApp] Notebook resnet/zztest_resnet_07-yolo544-0.5.ipynb is not trusted
[W 19:06:17.241 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.5-Copy1.ipynb
[I 19:06:23.337 NotebookApp] Copying resnet/zztest_resnet_07-yolo544-0.5-Copy1.ipynb to /resnet
[W 19:06:23.389 NotebookApp] Notebook resnet/zztest_resnet_07-yolo544-0.5-Copy1.ipynb is not trusted
[W 19:06:23.419 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.5-Copy2.ipynb
[W 19:06:54.334 NotebookApp] Notebook resnet/zztest_resnet_07-yolo544-0.0.ipynb is not trusted
[I 19:06:55.946 NotebookApp] Kernel started: c1c81629-9fff-42fa-bb8b-7db5959e6b0e
[I 19:07:38.691 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.0.ipynb
[W 19:07:38.692 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.0.ipynb
[I 19:07:52.426 NotebookApp] Kernel started: 9eb65aa6-4a93-4f16-9ada-c7619606ec51
[I 19:08:56.478 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.0.ipynb
[W 19:08:56.479 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.0.ipynb
[I 19:09:03.393 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.0.ipynb
[W 19:09:03.394 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.0.ipynb
[W 19:09:26.533 NotebookApp] Notebook resnet/zztest_resnet_07-yolo544-0.25.ipynb is not trusted
[I 19:09:31.355 NotebookApp] Kernel started: e682d7c4-95d7-4c25-ba09-295b76c4dd99
[W 19:09:31.638 NotebookApp] Notebook resnet/zztest_resnet_07-yolo544-0.5.ipynb is not trusted
[I 19:09:36.451 NotebookApp] Kernel started: 19a0bbb1-31e7-466e-837d-23156ee4c3bb
[I 19:11:22.794 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.25.ipynb
[W 19:11:22.795 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.25.ipynb
[I 19:11:56.597 NotebookApp] Kernel restarted: c1c81629-9fff-42fa-bb8b-7db5959e6b0e
[I 19:12:55.982 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.0.ipynb
[I 19:13:22.221 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.5.ipynb
[W 19:13:22.222 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.5.ipynb
[I 19:14:15.446 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.5.ipynb
[W 19:14:15.446 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.5.ipynb
[I 19:14:19.197 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.25.ipynb
[W 19:14:19.198 NotebookApp] Saving untrusted notebook resnet/zztest_resnet_07-yolo544-0.25.ipynb
[I 19:14:56.506 NotebookApp] Saving file at /resnet/zztest_resnet_07-yolo544-0.0.ipynb
